spring.application.name=dsa-daily-bot

# ==========================
# MySQL Configuration
# ==========================
spring.datasource.url=jdbc:mysql://localhost:3306/dsa_daily_bot
spring.datasource.username=root
spring.datasource.password=root

# ==========================
# JPA
# ==========================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# ==========================
# Flyway
# ==========================
spring.flyway.enabled=true
# ==========================
# Server
# ==========================
server.port=8080